// src/components/home/index.tsx
import {FunctionalComponent, h} from "preact";
import Discover from "../discover";
import Play from "../play";
import Title from "../title";
import * as style from "./style.css";
import AboutUs from "../about-us";
import Contact from "../contact";

const Home: FunctionalComponent = () => {
    return (
        <div className={style.home}>
            <Title/>
            <div className={style.container}>
                <Discover />
                <AboutUs/>
                <Contact/>
                <Play />
            </div>
        </div>
    );
};

export default Home;

// src/Home.svelte
<script>
	import AboutUs from "./AboutUs.svelte";
	import Contact from "./Contact.svelte";
	import Discover from "./Discover.svelte";
	import Play from "./Play.svelte";
	import Title from "./Title.svelte";
</script>

<div class="home">
	<Title />
	<div class="container">
		<Discover />
		<AboutUs />
		<Contact />
		<Play />
	</div>
</div>

<style>
	.home {
		min-height: 100%;
		width: 100%;
	}

	.container {
		width: 100%;
	}
</style>
